// <auto-generated />
using MVC_EF_Deneme.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_EF_Deneme.Migrations
{
    [DbContext(typeof(KargoContext))]
    [Migration("20200627104854_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_EF_Deneme.Models.Kargo", b =>
                {
                    b.Property<int>("kargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aliciBirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("aliciIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gonderenIsim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kargoId");

                    b.ToTable("Kargo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Kargo");
                });

            modelBuilder.Entity("MVC_EF_Deneme.Models.KargoDetay", b =>
                {
                    b.HasBaseType("MVC_EF_Deneme.Models.Kargo");

                    b.Property<string>("gonderenAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kargoAgirlik")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("KargoDetay");
                });
#pragma warning restore 612, 618
        }
    }
}
